### ISSUE TITLE
How to run bot?

### ISSUE THREAD

**Issue by andy1245** [Leaf48/Trading-bot#1]
Hi!
How can I run your bot?

**Comment by Leaf48** [comment]
You need a Python3.8.
The way to run is type "python smaema.py" or "python sanpei.py" in your console. 
But I highly recommend that you should not use this. Because it's no longer supported long time. And you may lose your money using this. 

Thanks.

**Comment by andy1245** [comment]
Thanks for your help. If I run sanpei.py i get an error:  
Traceback (most recent call last):
  File "sanpei.py", line 1020, in <module>
    main()
  File "sanpei.py", line 953, in main
    postWebhook(running, url)
  File "/home/alkoxy/tb/methods/DiscordWebhook.py", line 31, in postWebhook
    requests.post(url, json.dumps(content), headers={'Content-Type': 'application/json'})
  File "/home/alkoxy/.local/lib/python3.8/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/alkoxy/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/alkoxy/.local/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/alkoxy/.local/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/alkoxy/.local/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/home/alkoxy/.local/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

Any ideas, what I did wrong?

**Comment by Leaf48** [comment]
This bot is made on the premise that you are using Discord. 
You need to make Discord webhook. 
And then open “DiscordWebhook.py”, change the code ‘WEBHOOK=f””’ to ‘WEBHOOK=f”YOUR WEBHOOK URL”’.
